name: SLOW5 C/C++ CI Local OSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hdf5_compile:
    name: Linux hdf5 install script
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [macOS]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build
      run: autoreconf && ./scripts/install-hdf5.sh && ./configure --enable-localhdf5 && make -j8
    - name: test
      run: make test
