name: SLOW5 C/C++ CI Local

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  simple_install:
    name: Linux
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [linux-x86, linux-arm64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
    - name: build
      run: autoreconf && ./configure && make clean && make -j8
    - name: test
      run: make test
  hdf5_compile:
    name: Linux hdf5 install script
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [linux-x86, linux-arm64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
    - name: build
      run: autoreconf && ./scripts/install-hdf5.sh && ./configure --enable-localhdf5 && make clean && make -j8
    - name: test
      run: make test
    - name: valgrind
      run: ./test/test.sh mem
