name: SLOW5 C/C++ CI 2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  simple_install:
    name: Linux x86
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [linux-x86, linux-arm64]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: autoreconf && ./configure && make -j8
    - name: test
      run: make test
  hdf5_compile:
    name: Linux x86 hdf5 install script
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [linux-x86, linux-arm64]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: autoreconf && ./scripts/install-hdf5.sh && ./configure --enable-localhdf5 && make -j8
    - name: test
      run: make test
    - name: valgrind
      run: valgrind --leak-check=full --error-exitcode=1 ./slow5tools f2s test/data/raw/chr22_meth_example-subset-multi > /dev/null
  pyslow5:
    name: pyslow5 Linux x86
    runs-on: ${{ matrix.runners }}
    strategy:
      matrix:
        runners: [linux-x86, linux-arm64]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: autoreconf && ./configure && make pyslow5
