name: SlOW5 Cython CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu_16:
    name: Ubuntu 16
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libhdf5-dev python3-pip && pip3 install cython setuptools
    - name: build
      run: autoreconf && ./configure && make pyslow5
